# Generated by Django 4.1.5 on 2023-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
